// Canonical 66 Books of the Christian Bible with HTTLVN codes, OSIS codes, and translations
module.exports = [
  { order: 1, code: 'sa', osis: 'Gen', name_vi: 'Sáng-thế Ký', name_en: 'Genesis', testament: 'OT', chapterCount: 50 },
  { order: 2, code: 'xu', osis: 'Exod', name_vi: 'Xuất Ê-díp-tô Ký', name_en: 'Exodus', testament: 'OT', chapterCount: 40 },
  { order: 3, code: 'le', osis: 'Lev', name_vi: 'Lê-vi Ký', name_en: 'Leviticus', testament: 'OT', chapterCount: 27 },
  { order: 4, code: 'dan', osis: 'Num', name_vi: 'Dân-số Ký', name_en: 'Numbers', testament: 'OT', chapterCount: 36 },
  { order: 5, code: 'phu', osis: 'Deut', name_vi: 'Phục-truyền Luật-lệ Ký', name_en: 'Deuteronomy', testament: 'OT', chapterCount: 34 },
  { order: 6, code: 'gios', osis: 'Josh', name_vi: 'Giô-suê', name_en: 'Joshua', testament: 'OT', chapterCount: 24 },
  { order: 7, code: 'cac', osis: 'Judg', name_vi: 'Các Quan Xét', name_en: 'Judges', testament: 'OT', chapterCount: 21 },
  { order: 8, code: 'ru', osis: 'Ruth', name_vi: 'Ru-tơ', name_en: 'Ruth', testament: 'OT', chapterCount: 4 },
  { order: 9, code: '1sa', osis: '1Sam', name_vi: 'I Sa-mu-ên', name_en: '1 Samuel', testament: 'OT', chapterCount: 31 },
  { order: 10, code: '2sa', osis: '2Sam', name_vi: 'II Sa-mu-ên', name_en: '2 Samuel', testament: 'OT', chapterCount: 24 },
  { order: 11, code: '1vua', osis: '1Kgs', name_vi: 'I Các Vua', name_en: '1 Kings', testament: 'OT', chapterCount: 22 },
  { order: 12, code: '2vua', osis: '2Kgs', name_vi: 'II Các Vua', name_en: '2 Kings', testament: 'OT', chapterCount: 25 },
  { order: 13, code: '1su', osis: '1Chr', name_vi: 'I Sử-ký', name_en: '1 Chronicles', testament: 'OT', chapterCount: 29 },
  { order: 14, code: '2su', osis: '2Chr', name_vi: 'II Sử-ký', name_en: '2 Chronicles', testament: 'OT', chapterCount: 36 },
  { order: 15, code: 'exo', osis: 'Ezra', name_vi: 'E-xơ-ra', name_en: 'Ezra', testament: 'OT', chapterCount: 10 },
  { order: 16, code: 'ne', osis: 'Neh', name_vi: 'Nê-hê-mi', name_en: 'Nehemiah', testament: 'OT', chapterCount: 13 },
  { order: 17, code: 'et', osis: 'Esth', name_vi: 'Ê-xơ-tê', name_en: 'Esther', testament: 'OT', chapterCount: 10 },
  { order: 18, code: 'giop', osis: 'Job', name_vi: 'Gióp', name_en: 'Job', testament: 'OT', chapterCount: 42 },
  { order: 19, code: 'thi', osis: 'Ps', name_vi: 'Thi-thiên', name_en: 'Psalms', testament: 'OT', chapterCount: 150 },
  { order: 20, code: 'ch', osis: 'Prov', name_vi: 'Châm-ngôn', name_en: 'Proverbs', testament: 'OT', chapterCount: 31 },
  { order: 21, code: 'tr', osis: 'Eccl', name_vi: 'Truyền-đạo', name_en: 'Ecclesiastes', testament: 'OT', chapterCount: 12 },
  { order: 22, code: 'nha', osis: 'Song', name_vi: 'Nhã-ca', name_en: 'Song of Solomon', testament: 'OT', chapterCount: 8 },
  { order: 23, code: 'es', osis: 'Isa', name_vi: 'Ê-sai', name_en: 'Isaiah', testament: 'OT', chapterCount: 66 },
  { order: 24, code: 'gie', osis: 'Jer', name_vi: 'Giê-rê-mi', name_en: 'Jeremiah', testament: 'OT', chapterCount: 52 },
  { order: 25, code: 'ca', osis: 'Lam', name_vi: 'Ca-thương', name_en: 'Lamentations', testament: 'OT', chapterCount: 5 },
  { order: 26, code: 'exe', osis: 'Ezek', name_vi: 'Ê-xê-chi-ên', name_en: 'Ezekiel', testament: 'OT', chapterCount: 48 },
  { order: 27, code: 'da', osis: 'Dan', name_vi: 'Đa-ni-ên', name_en: 'Daniel', testament: 'OT', chapterCount: 12 },
  { order: 28, code: 'os', osis: 'Hos', name_vi: 'Ô-sê', name_en: 'Hosea', testament: 'OT', chapterCount: 14 },
  { order: 29, code: 'gio', osis: 'Joel', name_vi: 'Giô-ên', name_en: 'Joel', testament: 'OT', chapterCount: 3 },
  { order: 30, code: 'am', osis: 'Amos', name_vi: 'A-mốt', name_en: 'Amos', testament: 'OT', chapterCount: 9 },
  { order: 31, code: 'ap', osis: 'Obad', name_vi: 'Áp-đia', name_en: 'Obadiah', testament: 'OT', chapterCount: 1 },
  { order: 32, code: 'gion', osis: 'Jonah', name_vi: 'Giô-na', name_en: 'Jonah', testament: 'OT', chapterCount: 4 },
  { order: 33, code: 'mi', osis: 'Mic', name_vi: 'Mi-chê', name_en: 'Micah', testament: 'OT', chapterCount: 7 },
  { order: 34, code: 'na', osis: 'Nah', name_vi: 'Na-hum', name_en: 'Nahum', testament: 'OT', chapterCount: 3 },
  { order: 35, code: 'ha', osis: 'Hab', name_vi: 'Ha-ba-cúc', name_en: 'Habakkuk', testament: 'OT', chapterCount: 3 },
  { order: 36, code: 'so', osis: 'Zeph', name_vi: 'Sô-phô-ni', name_en: 'Zephaniah', testament: 'OT', chapterCount: 3 },
  { order: 37, code: 'ag', osis: 'Hag', name_vi: 'A-ghê', name_en: 'Haggai', testament: 'OT', chapterCount: 2 },
  { order: 38, code: 'xa', osis: 'Zech', name_vi: 'Xa-cha-ri', name_en: 'Zechariah', testament: 'OT', chapterCount: 14 },
  { order: 39, code: 'ma', osis: 'Mal', name_vi: 'Ma-la-chi', name_en: 'Malachi', testament: 'OT', chapterCount: 4 },
  { order: 40, code: 'mat', osis: 'Matt', name_vi: 'Ma-thi-ơ', name_en: 'Matthew', testament: 'NT', chapterCount: 28 },
  { order: 41, code: 'mac', osis: 'Mark', name_vi: 'Mác', name_en: 'Mark', testament: 'NT', chapterCount: 16 },
  { order: 42, code: 'lu', osis: 'Luke', name_vi: 'Lu-ca', name_en: 'Luke', testament: 'NT', chapterCount: 24 },
  { order: 43, code: 'gi', osis: 'John', name_vi: 'Giăng', name_en: 'John', testament: 'NT', chapterCount: 21 },
  { order: 44, code: 'cong', osis: 'Acts', name_vi: 'Công-vụ các Sứ-đồ', name_en: 'Acts', testament: 'NT', chapterCount: 28 },
  { order: 45, code: 'ro', osis: 'Rom', name_vi: 'Rô-ma', name_en: 'Romans', testament: 'NT', chapterCount: 16 },
  { order: 46, code: '1co', osis: '1Cor', name_vi: 'I Cô-rinh-tô', name_en: '1 Corinthians', testament: 'NT', chapterCount: 16 },
  { order: 47, code: '2co', osis: '2Cor', name_vi: 'II Cô-rinh-tô', name_en: '2 Corinthians', testament: 'NT', chapterCount: 13 },
  { order: 48, code: 'ga', osis: 'Gal', name_vi: 'Ga-la-ti', name_en: 'Galatians', testament: 'NT', chapterCount: 6 },
  { order: 49, code: 'eph', osis: 'Eph', name_vi: 'Ê-phê-sô', name_en: 'Ephesians', testament: 'NT', chapterCount: 6 },
  { order: 50, code: 'phi', osis: 'Phil', name_vi: 'Phi-líp', name_en: 'Philippians', testament: 'NT', chapterCount: 4 },
  { order: 51, code: 'co', osis: 'Col', name_vi: 'Cô-lô-se', name_en: 'Colossians', testament: 'NT', chapterCount: 4 },
  { order: 52, code: '1te', osis: '1Thess', name_vi: 'I Tê-sa-lô-ni-ca', name_en: '1 Thessalonians', testament: 'NT', chapterCount: 5 },
  { order: 53, code: '2te', osis: '2Thess', name_vi: 'II Tê-sa-lô-ni-ca', name_en: '2 Thessalonians', testament: 'NT', chapterCount: 3 },
  { order: 54, code: '1ti', osis: '1Tim', name_vi: 'I Ti-mô-thê', name_en: '1 Timothy', testament: 'NT', chapterCount: 6 },
  { order: 55, code: '2ti', osis: '2Tim', name_vi: 'II Ti-mô-thê', name_en: '2 Timothy', testament: 'NT', chapterCount: 4 },
  { order: 56, code: 'tit', osis: 'Titus', name_vi: 'Tít', name_en: 'Titus', testament: 'NT', chapterCount: 3 },
  { order: 57, code: 'phil', osis: 'Phlm', name_vi: 'Phi-lê-môn', name_en: 'Philemon', testament: 'NT', chapterCount: 1 },
  { order: 58, code: 'he', osis: 'Heb', name_vi: 'Hê-bơ-rơ', name_en: 'Hebrews', testament: 'NT', chapterCount: 13 },
  { order: 59, code: 'gia', osis: 'Jas', name_vi: 'Gia-cơ', name_en: 'James', testament: 'NT', chapterCount: 5 },
  { order: 60, code: '1phi', osis: '1Pet', name_vi: 'I Phi-e-rơ', name_en: '1 Peter', testament: 'NT', chapterCount: 5 },
  { order: 61, code: '2phi', osis: '2Pet', name_vi: 'II Phi-e-rơ', name_en: '2 Peter', testament: 'NT', chapterCount: 3 },
  { order: 62, code: '1gi', osis: '1John', name_vi: 'I Giăng', name_en: '1 John', testament: 'NT', chapterCount: 5 },
  { order: 63, code: '2gi', osis: '2John', name_vi: 'II Giăng', name_en: '2 John', testament: 'NT', chapterCount: 1 },
  { order: 64, code: '3gi', osis: '3John', name_vi: 'III Giăng', name_en: '3 John', testament: 'NT', chapterCount: 1 },
  { order: 65, code: 'giu', osis: 'Jude', name_vi: 'Giu-đe', name_en: 'Jude', testament: 'NT', chapterCount: 1 },
  { order: 66, code: 'kh', osis: 'Rev', name_vi: 'Khải-huyền', name_en: 'Revelation', testament: 'NT', chapterCount: 22 }
];
